<!DOCTYPE html>
<?php
if (!isset($_POST['send']))
	$send=0;
else
	$send=$_POST['send'];
	
if ($send==0)
{
	header("Location:list.php");
	exit;	
}

echo"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n<html>\n";
echo"<head>\n<title>Report visit</title>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\n</head>\n<body>\n";
if (!isset($_POST['last']))
	$last =" ";
else
	$last=$_POST['last'];
if (!isset($_POST['first']))
	$first =" ";
else
	$first=$_POST['first'];
if (!isset($_POST['address']))
	$address =" ";
else
	$address=$_POST['address'];
if (!isset($_POST['telephone']))
	$telephone =" ";
else
	$telephone=$_POST['telephone'];
if (!isset($_POST['info']))
	$info =" ";
else
	$info=$_POST['info'];
if (!isset($_POST['vincentian']))
	$vincentian =" ";
else
	$vincentian=$_POST['vincentian'];
if (!isset($_POST['visitdate']))
	$visitdate =" ";
else
	$visitdate=$_POST['visitdate'];

$vemail=$_POST['vemail'];


echo"<table border=1 cellpadding='10' cellspacing='0' bgcolor='#31a0ff'><tr><td align='center'><img src='images/svdp.jpg' width='699' height='94'><br>\n";
$message1 = "This message is automatically generated by the Vincentian Website, St. John the Evangelist, Whitby\n\n";
$message2 = "This is to confirm that you sent this message to the current administrator\n\n";
$message = "Client name: (first) $first, (last) $last\nCurrent address: $address\nCurrent telephone: $telephone\n";
$message.= "Visited by: $vincentian on: $visitdate\n\n";
$message.= "Report:\n $info\n";

$vincentians = array ();
$n=strpos($svdp,"svdp",0);// "svdp" is the delimiter for the numeric code of the vincentian
$m=substr($svdp,1,$n-1);//numeric code for the vincentian
$f=fopen("data/svpw.txt","r");
while( !feof($f))
{
	$line = fgets($f,1000);
	$vincentians =explode("\t",$line);//field 0=id; 1=pw; 2=access level; 3=last name; 4=first name; 5=email
	if ($vincentians[2]=="a")
		if (strlen($vemail)>5)
			mail($vincentians[5],"St Vincent de Paul Update",$message1.$message,"From: $vemail");
		else
			mail($vincentians[5],"St Vincent de Paul Update",$message1.$message,"From: svdp@sjewhitby.ca");
}
fclose($f);

if (strlen($vemail)>5)
	mail($vemail,"St Vincent de Paul Update",$message2.$message,"From: svdp@sjewhitby.ca");
echo"<font size=3>Your message has been sent to the curent Administrator(s)\nThank you.</font><br><br>\n";
echo"<a href='list.php'><img src='images/nosend.gif' border=0></a>";
echo"</td></tr></table></body></html>\n";

?>